/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package smsender;

import au.com.bytecode.opencsv.CSVReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Joel
 */
public class CustomMsgForm extends javax.swing.JDialog {

    /**
     * Creates new form CustomMsgForm
     */
    String ProjectPath, CustomMsgCSVFilePath;
    String[] headerrow, nextline;

    public CustomMsgForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        ProjectPath = new File("").getAbsolutePath();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTxtMessage = new javax.swing.JTextArea();
        jBtnCustomMsg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Custom Message");

        jTxtMessage.setColumns(20);
        jTxtMessage.setRows(5);
        jScrollPane5.setViewportView(jTxtMessage);

        jBtnCustomMsg.setText("Custom Message");
        jBtnCustomMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCustomMsgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCustomMsg))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnCustomMsg)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCustomMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCustomMsgActionPerformed
        if (!jTxtMessage.getText().equals("")) {
            int a = JOptionPane.showConfirmDialog(this, "Do you want to send a custom message", "Confimation", JOptionPane.YES_NO_OPTION);
            if (a == JOptionPane.YES_OPTION) {
                try {
                    String message;
                    JFileChooser chooser = new JFileChooser();
                    chooser.setCurrentDirectory(new File(ProjectPath));
                    chooser.setDialogTitle("Select CSV File");
                    FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV", "csv");
                    chooser.setFileFilter(filter);
                    int counter = chooser.showDialog(this, "Open");
                    if (counter == 0) {
                        CustomMsgCSVFilePath = chooser.getSelectedFile().getPath();
                    }
                    CSVReader csvr = new CSVReader(new FileReader(CustomMsgCSVFilePath), ',');
                    headerrow = csvr.readNext();
                    if (headerrow == null) {
                        throw new FileNotFoundException("No columns defined in given CSV file." + "Please check the CSV file format.");
                    }
                    while ((nextline = csvr.readNext()) != null) {
                        message = jTxtMessage.getText();
                        for (int i = 1; i < nextline.length; i++) {
                            message = message.replaceAll("<<" + headerrow[i] + ">>", nextline[i]);
                        }
                        System.out.println(message);
                        //                         msg = new OutboundMessage("+91" + nextline[0], message);
                        //                        Service.getInstance().queueMessage(msg, gateway.getGatewayId());
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "No message composed", "Message", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBtnCustomMsgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomMsgForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomMsgForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomMsgForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomMsgForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomMsgForm dialog = new CustomMsgForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCustomMsg;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTxtMessage;
    // End of variables declaration//GEN-END:variables
}
